#!/bin/bash
# =====================================================
# custom-layout-guide.sh - Guía para layouts personalizables
# =====================================================

echo "🎨 ¡SISTEMA DE LAYOUTS PERSONALIZABLES DE NEOVIM!"
echo "================================================"
echo ""

echo "✨ Ahora tienes TOTAL FLEXIBILIDAD para crear layouts a tu medida:"
echo ""

echo "📋 MÉTODO 1: PASO A PASO INTERACTIVO"
echo "-----------------------------------"
echo "1. 🚀 <Space>lc  → Iniciar layout personalizado"
echo "2. 📐 <Space>ln  → Ver opciones del siguiente paso"
echo "3. ➖ <Space>lH  → División horizontal"
echo "4. ➗ <Space>lV  → División vertical"  
echo "5. 💻 <Space>lT  → Terminal en ventana actual"
echo "6. 📝 <Space>le  → Editor en ventana actual"
echo "7. 📏 <Space>lr  → Redimensionar ventana"
echo "8. ✅ <Space>ld  → Terminar layout"
echo ""

echo "💾 GUARDAR Y CARGAR LAYOUTS"
echo "---------------------------"
echo "• 💾 <Space>ls  → Guardar layout actual con nombre"
echo "• 📂 <Space>ll  → Cargar layout guardado"
echo "• 🗂️  <Space>lm  → Gestionar layouts guardados"
echo ""

echo "⚡ DIVISIONES RÁPIDAS (sin asistente)"
echo "------------------------------------"
echo "• ➖ <Space>lh  → División horizontal directa"
echo "• ➗ <Space>lv  → División vertical directa"
echo "• 💻 <Space>lt  → Terminal aquí directamente"
echo ""

echo "🎯 LAYOUTS PREDEFINIDOS (para comparar)"
echo "---------------------------------------"
echo "• 🏠 <Space>dl  → Tu layout específico (4 ventanas)"
echo "• 📱 <Space>ds  → Layout simple (editor + terminal)"
echo "• 📺 <Space>dd  → Layout lateral"
echo "• 🖥️  <Space>dt  → Layout triple"
echo ""

echo "🌟 EJEMPLO DE FLUJO DE TRABAJO:"
echo "------------------------------"
echo ""
echo "Supongamos que quieres crear un layout específico para debugging:"
echo ""
echo "1. nvim mi_archivo.py"
echo "2. <Space>lc                    (Iniciar layout personalizado)"
echo "3. <Space>lV                    (División vertical)"
echo "4. <Space>le                    (Editor en ventana derecha)"  
echo "5. <Space>1                     (Ir a ventana izquierda)"
echo "6. <Space>lH                    (División horizontal en izquierda)"
echo "7. <Space>lT                    (Terminal superior izquierda)"
echo "8. <Space>3                     (Ir a ventana inferior izquierda)"
echo "9. <Space>lT                    (Terminal inferior izquierda)"
echo "10. <Space>ld                   (Terminar layout)"
echo "11. <Space>ls                   (Guardar como 'debug-layout')"
echo ""

echo "🎭 RESULTADO DEL EJEMPLO ANTERIOR:"
echo ""
echo "┌─────────────┬─────────────┐"
echo "│ Terminal 1  │             │"
echo "│ (logs)      │   EDITOR    │"
echo "├─────────────┤   PRINCIPAL │"
echo "│ Terminal 2  │             │"
echo "│ (debug)     │             │"
echo "└─────────────┴─────────────┘"
echo ""

echo "💡 CONSEJOS PRO:"
echo "---------------"
echo "• Cada terminal creado con <Space>lT se guarda automáticamente"
echo "• Usa <Space>lr para ajustar tamaños perfectamente"
echo "• Los layouts guardados se almacenan en ~/.config/nvim/layouts/"
echo "• Puedes crear tantos layouts como necesites para diferentes tareas"
echo "• Los layouts se restauran con todas las divisiones y terminales"
echo ""

echo "🚀 ¡PRUEBA AHORA!"
echo "cd /home/jose/test-python"
echo "nvim test_layout_demo.py"
echo ""
echo "Después en Neovim:"
echo "<Space>lc  (iniciar)"
echo "<Space>ln  (ver opciones)"
echo ""

echo "¿Listo para crear layouts a tu medida? 🎨✨"
